" .vimrc
set nocompatible                "Turn off compability mode with Vi, we don't need that anymore

execute pathogen#infect('base/{}')
if isdirectory(expand("$HOME/.vim/custom/"))
  execute pathogen#infect('custom/{}')
  source $HOME/.vim/custom/vimrc
endif
execute pathogen#helptags()
syntax on
filetype plugin indent on

" check for ctags folder, if not exist extract our ctags binary
if !isdirectory(expand("$HOME/.vim/binary/ctags/"))
	let ctags_bottle_dir =  expand("$HOME/.vim/binary/")
	let ctags_bottle_file = expand("$HOME/.vim/binary/ctags-5.8.mountain_lion.bottle.tar.gz")
	execute "cd ".ctags_bottle_dir
	execute "!tar xfv ".ctags_bottle_file
endif

set noerrorbells                " No beeps
set number                      " Show line numbers
set backspace=indent,eol,start  " Makes backspace key more powerful.
set showcmd                     " Show me what I'm typing
set showmode                    " Show current mode.

set noswapfile                  " Don't use swapfile
set nobackup            		" Don't create annoying backup files
set splitright                  " Split vertical windows right to the current windows
set splitbelow                  " Split horizontal windows below to the current windows
set encoding=utf-8              " Set default encoding to UTF-8
set autowrite                   " Automatically save before :next, :make etc.
set autoread                    " Automatically reread changed files without asking me anything
set laststatus=2

set fileformats=unix,dos,mac    " Prefer Unix over Windows over OS 9 formats

set showmatch                   " Do not show matching brackets by flickering
set incsearch                   " Shows the match while typing
set hlsearch                    " Highlight found searches
set ignorecase                  " Search case insensitive...
set smartcase                   " ... but not when search pattern contains upper case characters


" ----------------------------------------------"
" MacVim modifications (color, shortcuts, etc.. "
" ----------------------------------------------"
"http://stackoverflow.com/questions/14802689/macvim-wont-load-specific-color-scheme-by-default
let macvim_skip_colorscheme=1
let g:molokai_original=1
colorscheme molokai
highlight SignColumn guibg=#272822   

if has("gui_macvim")
  " No toolbars, menu or scrollbars in the GUI
  set guifont=Source\ Code\ Pro\ for\ Powerline:h13
  set clipboard+=unnamed
  set vb t_vb=
  set guioptions-=m  "no menu
  set guioptions-=T  "no toolbar
  set guioptions-=l
  set guioptions-=L
  set guioptions-=r  "no scrollbar
  set guioptions-=R

  " Open ctrlp with cmd+p
  let g:ctrlp_map = '<D-p>'

  " Open Go to symbol (via tags)
  nmap <D-r> :MyCtrlPTag<cr>
  nmap <D-R> :CtrlPBufTagAll<cr>

  " Go to file
  nmap <D-t> :CtrlP<cr>

  " Move  with cmd+alt
  nmap <D-M-RIGHT> gt
  nmap <D-M-LEFT> gT

  " Comment lines with cmd+/
  map <D-/> :TComment<cr>
  vmap <D-/> :TComment<cr>gv

  " Indent lines with cmd+[ and cmd+]
  nmap <D-]> >>
  nmap <D-[> <<
  vmap <D-[> <gv
  vmap <D-]> >gv

  "Open sidebar with cmd+k
  map <D-k> :NERDTreeTabsToggle<CR>

  "switch between tabs with cmd+1, cmd+2,..."
  map <D-1> :tabfirst<Cr>
  map <D-2> :tabfirst<Cr>gt
  map <D-3> :tabfirst<Cr>3gt
  map <D-4> :tabfirst<Cr>4gt
  map <D-5> :tabfirst<Cr>5gt
  map <D-6> :tabfirst<Cr>6gt
  map <D-7> :tabfirst<Cr>7gt
  map <D-8> :tabfirst<Cr>8gt
  map <D-9> :tabfirst<Cr>9gt

  imap <D-1> <esc>:tabfirst<Cr>
  imap <D-2> <esc>:tabfirst<Cr>gt
  imap <D-3> <esc>:tabfirst<Cr>3gt
  imap <D-4> <esc>:tabfirst<Cr>4gt
  imap <D-5> <esc>:tabfirst<Cr>5gt
  imap <D-6> <esc>:tabfirst<Cr>6gt
  imap <D-7> <esc>:tabfirst<Cr>7gt
  imap <D-8> <esc>:tabfirst<Cr>8gt
  imap <D-9> <esc>:tabfirst<Cr>9gt

  " Stop completion with enter, in addition to default ctrl+y
  imap <expr> <CR> pumvisible() ? "\<c-y>" : "<Plug>delimitMateCR"

endif

" ----------------------------------------- "
" Plugin configs 			    			"
" ----------------------------------------- "

let g:ctrlp_cmd = 'CtrlPMixed'			" search anything (in files, buffers and MRU files at the same time.)
let g:ctrlp_working_path_mode = 'ra'	" search for nearest ancestor like .git, .hg, and the directory of the current file
let g:ctrlp_match_window_bottom = 0		" show the match window at the top of the screen
let g:ctrlp_max_height = 10				" maxiumum height of match window
let g:ctrlp_switch_buffer = 'et'		" jump to a file if it's open already
let g:ctrlp_use_caching = 1				" enable caching
let g:ctrlp_clear_cache_on_exit=0  		" speed up by not removing clearing cache evertime
let g:ctrlp_show_hidden = 1				" show me dotfiles
let g:ctrlp_mruf_max = 250 				" number of recently opened files

func! MyPrtMappings()
    let g:ctrlp_prompt_mappings = {
        \ 'AcceptSelection("e")': ['<c-t>'],
        \ 'AcceptSelection("t")': ['<cr>', '<2-LeftMouse>'],
        \ }
endfunc

func! MyCtrlPTag()
    let g:ctrlp_prompt_mappings = {
        \ 'AcceptSelection("e")': ['<cr>', '<2-LeftMouse>'],
        \ 'AcceptSelection("t")': ['<c-t>'],
        \ }
    CtrlPBufTag
endfunc

let g:ctrlp_buffer_func = { 'exit': 'MyPrtMappings' }
com! MyCtrlPTag call MyCtrlPTag()

" TODO: add javascript and some other languages who doesn't have ctags support
" coffee: https://gist.github.com/michaelglass/5210282
" go: http://stackoverflow.com/a/8236826/462233 
" objc:  http://www.gregsexton.org/2011/04/objective-c-exuberant-ctags-regex/
" rust: https://github.com/mozilla/rust/blob/master/src/etc/ctags.rust
let g:ctrlp_buftag_types = {
\ 'go'     	   : '--language-force=go --golang-types=ftv',
\ 'coffee'     : '--language-force=coffee --coffee-types=cmfvf',
\ 'markdown'   : '--language-force=markdown --markdown-types=hik',
\ 'objc'       : '--language-force=objc --objc-types=mpci',
\ 'rc'         : '--language-force=rust --rust-types=fTm'
\ }


let g:Powerline_symbols = 'fancy'

let g:ycm_autoclose_preview_window_after_completion = 1

let g:session_autosave = 'yes'
let g:session_autoload = 'yes'
let g:session_default_to_last = 1

"create line break when pressing enter
let g:delimitMate_expand_cr = 1
let g:delimitMate_expand_space = 1

let g:nerdtree_tabs_open_on_gui_startup = 0
